<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountValues;

use Atlas\Table\Table;

/**
 * @method AccountValuesRow|null fetchRow($primaryVal)
 * @method AccountValuesRow[] fetchRows(array $primaryVals)
 * @method AccountValuesTableSelect select(array $whereEquals = [])
 * @method AccountValuesRow newRow(array $cols = [])
 * @method AccountValuesRow newSelectedRow(array $cols)
 */
class AccountValuesTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'account_values';

    const COLUMNS = [
        'account_id' => [
            'name' => 'account_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'value_key' => [
            'name' => 'value_key',
            'type' => 'varchar',
            'size' => 128,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'value_data' => [
            'name' => 'value_data',
            'type' => 'mediumtext',
            'size' => 16777215,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'value_idx' => [
            'name' => 'value_idx',
            'type' => 'varchar',
            'size' => 128,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'encrypted' => [
            'name' => 'encrypted',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => '0',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'modified' => [
            'name' => 'modified',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'account_id',
        'value_key',
        'value_data',
        'value_idx',
        'encrypted',
        'modified',
    ];

    const COLUMN_DEFAULTS = [
        'account_id' => null,
        'value_key' => null,
        'value_data' => null,
        'value_idx' => null,
        'encrypted' => '0',
        'modified' => null,
    ];

    const PRIMARY_KEY = [
        'account_id',
        'value_key',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
