<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountValues;

use Atlas\Table\Row;

/**
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $value_key varchar(128) NOT NULL
 * @property mixed $value_data mediumtext(16777215) NOT NULL
 * @property mixed $value_idx varchar(128)
 * @property mixed $encrypted tinyint(3,0) NOT NULL
 * @property mixed $modified datetime NOT NULL
 */
class AccountValuesRow extends Row
{
    protected $cols = [
        'account_id' => null,
        'value_key' => null,
        'value_data' => null,
        'value_idx' => null,
        'encrypted' => '0',
        'modified' => null,
    ];
}
