<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountToken;

use Atlas\Table\Table;

/**
 * @method AccountTokenRow|null fetchRow($primaryVal)
 * @method AccountTokenRow[] fetchRows(array $primaryVals)
 * @method AccountTokenTableSelect select(array $whereEquals = [])
 * @method AccountTokenRow newRow(array $cols = [])
 * @method AccountTokenRow newSelectedRow(array $cols)
 */
class AccountTokenTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'account_tokens';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'account_id' => [
            'name' => 'account_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'provider' => [
            'name' => 'provider',
            'type' => 'varchar',
            'size' => 128,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'uid' => [
            'name' => 'uid',
            'type' => 'mediumtext',
            'size' => 16777215,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'token' => [
            'name' => 'token',
            'type' => 'mediumtext',
            'size' => 16777215,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'last_use' => [
            'name' => 'last_use',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'expire' => [
            'name' => 'expire',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'account_id',
        'provider',
        'uid',
        'token',
        'last_use',
        'expire',
        'created',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'account_id' => null,
        'provider' => null,
        'uid' => null,
        'token' => null,
        'last_use' => null,
        'expire' => null,
        'created' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
