<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountToken;

use Atlas\Table\Row;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $provider varchar(128) NOT NULL
 * @property mixed $uid mediumtext(16777215) NOT NULL
 * @property mixed $token mediumtext(16777215) NOT NULL
 * @property mixed $last_use datetime NOT NULL
 * @property mixed $expire datetime NOT NULL
 * @property mixed $created datetime NOT NULL
 */
class AccountTokenRow extends Row
{
    protected $cols = [
        'id' => null,
        'account_id' => null,
        'provider' => null,
        'uid' => null,
        'token' => null,
        'last_use' => null,
        'expire' => null,
        'created' => null,
    ];
}
