<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\Account;

use Atlas\Table\Table;

/**
 * @method AccountRow|null fetchRow($primaryVal)
 * @method AccountRow[] fetchRows(array $primaryVals)
 * @method AccountTableSelect select(array $whereEquals = [])
 * @method AccountRow newRow(array $cols = [])
 * @method AccountRow newSelectedRow(array $cols)
 */
class AccountTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'accounts';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'secret' => [
            'name' => 'secret',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'deleted' => [
            'name' => 'deleted',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'status' => [
            'name' => 'status',
            'type' => 'enum',
            'size' => 9,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => 
  array (
    0 => '\'approved\'',
    1 => '\'pending\'',
    2 => '\'blocked\'',
    3 => '\'invited\'',
    4 => '\'temporary\'',
    5 => '\'deleted\'',
  ),
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'secret',
        'created',
        'deleted',
        'status',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'secret' => null,
        'created' => null,
        'deleted' => null,
        'status' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
