<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AclRoleAcces;

/**
 * @property mixed $role_id bigint(20,0) unsigned NOT NULL
 * @property mixed $access_key varchar(64) NOT NULL
 * @property mixed $access enum(8) NOT NULL
 * @property mixed $modified datetime NOT NULL
 */
trait AclRoleAccesFields
{
}
