<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AclRoleAcces;

use Atlas\Table\Table;

/**
 * @method AclRoleAccesRow|null fetchRow($primaryVal)
 * @method AclRoleAccesRow[] fetchRows(array $primaryVals)
 * @method AclRoleAccesTableSelect select(array $whereEquals = [])
 * @method AclRoleAccesRow newRow(array $cols = [])
 * @method AclRoleAccesRow newSelectedRow(array $cols)
 */
class AclRoleAccesTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'acl_role_access';

    const COLUMNS = [
        'role_id' => [
            'name' => 'role_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'access_key' => [
            'name' => 'access_key',
            'type' => 'varchar',
            'size' => 64,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'access' => [
            'name' => 'access',
            'type' => 'enum',
            'size' => 8,
            'scale' => null,
            'notnull' => true,
            'default' => 'denied',
            'autoinc' => false,
            'primary' => false,
            'options' => 
  array (
    0 => '\'approved\'',
    1 => '\'denied\'',
  ),
        ],
        'modified' => [
            'name' => 'modified',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'role_id',
        'access_key',
        'access',
        'modified',
    ];

    const COLUMN_DEFAULTS = [
        'role_id' => null,
        'access_key' => null,
        'access' => 'denied',
        'modified' => null,
    ];

    const PRIMARY_KEY = [
        'role_id',
        'access_key',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
