<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountLoginLog;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $login_time datetime NOT NULL
 * @property mixed $ip text(65535) NOT NULL
 * @property mixed $ip_idx text(65535) NOT NULL
 * @property mixed $ua int(10,0) NOT NULL
 * @property mixed $provider varchar(64)
 * @property mixed $status varchar(64)
 */
trait AccountLoginLogFields
{
}
