<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AclRole;

use Atlas\Table\Table;

/**
 * @method AclRoleRow|null fetchRow($primaryVal)
 * @method AclRoleRow[] fetchRows(array $primaryVals)
 * @method AclRoleTableSelect select(array $whereEquals = [])
 * @method AclRoleRow newRow(array $cols = [])
 * @method AclRoleRow newSelectedRow(array $cols)
 */
class AclRoleTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'acl_roles';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'varchar',
            'size' => 128,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'modified' => [
            'name' => 'modified',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'created',
        'modified',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'created' => null,
        'modified' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
