<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AclRole;

use Atlas\Table\Row;

/**
 * @property mixed $id bigint(20,0) unsigned NOT NULL
 * @property mixed $name varchar(128) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $modified datetime NOT NULL
 */
class AclRoleRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
        'created' => null,
        'modified' => null,
    ];
}
