<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountRole;

/**
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $role_id bigint(20,0) unsigned NOT NULL
 */
trait AccountRoleFields
{
}
