<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountRole;

use Atlas\Table\Table;

/**
 * @method AccountRoleRow|null fetchRow($primaryVal)
 * @method AccountRoleRow[] fetchRows(array $primaryVals)
 * @method AccountRoleTableSelect select(array $whereEquals = [])
 * @method AccountRoleRow newRow(array $cols = [])
 * @method AccountRoleRow newSelectedRow(array $cols)
 */
class AccountRoleTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'account_roles';

    const COLUMNS = [
        'account_id' => [
            'name' => 'account_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'role_id' => [
            'name' => 'role_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'account_id',
        'role_id',
    ];

    const COLUMN_DEFAULTS = [
        'account_id' => null,
        'role_id' => null,
    ];

    const PRIMARY_KEY = [
        'account_id',
        'role_id',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
