<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountAccess;

use Atlas\Table\Row;

/**
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $access_key varchar(128) NOT NULL
 * @property mixed $access enum(8) NOT NULL
 */
class AccountAccessRow extends Row
{
    protected $cols = [
        'account_id' => null,
        'access_key' => null,
        'access' => 'denied',
    ];
}
