<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountAccess;

/**
 * @property mixed $account_id bigint(20,0) unsigned NOT NULL
 * @property mixed $access_key varchar(128) NOT NULL
 * @property mixed $access enum(8) NOT NULL
 */
trait AccountAccessFields
{
}
