<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Circli\Modules\Auth\DataSource\AccountAccess;

use Atlas\Table\Table;

/**
 * @method AccountAccessRow|null fetchRow($primaryVal)
 * @method AccountAccessRow[] fetchRows(array $primaryVals)
 * @method AccountAccessTableSelect select(array $whereEquals = [])
 * @method AccountAccessRow newRow(array $cols = [])
 * @method AccountAccessRow newSelectedRow(array $cols)
 */
class AccountAccessTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'account_access';

    const COLUMNS = [
        'account_id' => [
            'name' => 'account_id',
            'type' => 'bigint unsigned',
            'size' => 20,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'access_key' => [
            'name' => 'access_key',
            'type' => 'varchar',
            'size' => 128,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'access' => [
            'name' => 'access',
            'type' => 'enum',
            'size' => 8,
            'scale' => null,
            'notnull' => true,
            'default' => 'denied',
            'autoinc' => false,
            'primary' => false,
            'options' => 
  array (
    0 => '\'approved\'',
    1 => '\'denied\'',
  ),
        ],
    ];

    const COLUMN_NAMES = [
        'account_id',
        'access_key',
        'access',
    ];

    const COLUMN_DEFAULTS = [
        'account_id' => null,
        'access_key' => null,
        'access' => 'denied',
    ];

    const PRIMARY_KEY = [
        'account_id',
        'access_key',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
